sudo: false
dist: trusty
language: node_js
node_js:
  - 12
cache: npm

before_script:
  - npm install
  - npm install -g gitbook-cli
  - export PATH=$(npm bin):$PATH

script:
  - gitbook build . --gitbook=3.2.3

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: _book
  on:
    branch: master
